config/routes.rb
WeeklyReport::Application.routes.draw do
  match '/contact', :to => 'pages#contact'

 root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
# -*- encoding : utf-8 -*-
class PagesController < ApplicationController
  def home
    @title = "Главная"
  end

  def contact
    @title = "Контакты"
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  
  # return a title on a per-page basis.
  def title
    base_title = "Информация регистратора"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print'%>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
      <header>
        <h1>Еженедельный отчет</h1>
      </header>
      <nav>
          <ul>
            <li><%= link_to "Главная", root_path %></li>
            <li><%= link_to "Контакты", contact_path %></li>
          </ul>
      </nav>
      <section class="container">
        <%= yield %>
      </section>
    <footer>
      <h6>Днепрпетровск</h6>
      <h6>2012г.</h6> 
    </footer>
  </body>
</html>

app/views/pages/contact.html.erb
    <h1>Если возникли вопросы, обращайтесь:</h1>
    <p>контакты...........контакты...........контакты...........контакты...........контакты...........
       контакты...........контакты...........контакты...........контакты...........контакты...........
       контакты...........контакты...........контакты...........контакты...........контакты...........
    </p>

app/views/pages/home.html.erb
    <h1>Актуальный отчет по компаниям</h1>
    <p>таблична...........таблична...........таблична...........таблична...........таблична...........
    таблична...........таблична...........таблична...........таблична...........таблична...........
    таблична...........таблична...........таблична...........таблична...........таблична...........
    таблична...........таблична...........таблична...........таблична...........таблична...........
    </p>